#!/bin/bash


# This script reads checks whether 
# the first argument is greater than 3
# Example run:
#    bash example_if 7


# For numbers 
# ===================  =======  
# Equals                 -eq    
# Not Equals             -ne    
# Greater Than           -gt    
# Less Than              -lt    
# Greater or Equals      -ge    
# Less Than or Equals    -le    

# $1 is the first argument to the script

if [ $1 -gt 3 ]; then
  echo $1 " is greater than 3"
else
  echo $1 " is less than 3"
fi
